apiVersion: app.azure.microsoft.com/v1
kind: TracingPinger
metadata:
  labels:
    app.kubernetes.io/name: example-operator
    app.kubernetes.io/managed-by: kustomize
  name: pinger1
  namespace: monitoring
spec:
  value: 0
